.. package: qgis\.core

Class: QgsProviderConnectionException
...............................................

.. py:module:: QgsProviderConnectionException

.. autoclass:: qgis.core.QgsProviderConnectionException
   :special-members: __init__
   :members:
   :undoc-members:

    .. autoautosummary:: qgis.core.QgsProviderConnectionException
        :enums:
        :nosignatures:

    .. autoautosummary:: qgis.core.QgsProviderConnectionException
        :methods:
        :nosignatures:

    .. autoautosummary:: qgis.core.QgsProviderConnectionException
        :signals:
        :nosignatures:

    .. autoautosummary:: qgis.core.QgsProviderConnectionException
        :attributes:

